### ISSUE TITLE
notifier fails when big message

### ISSUE THREAD

**Issue by pavelloz** [mdyd-dev/pos-cli#186]
When message is bigger than X notifier will throw error.

If it happen during logs (which mean log entry is big) it will hug as much network transfer as it can. It used 3.5MBps in my case for half an hour until i noticed. 

### Marketplace Kit
2.7.8

### NodeJs
10.15.3

### Operating System
OSX

```
Unhandled rejection Error: spawn E2BIG
   at ChildProcess.spawn (internal/child_process.js:366:11)
   at spawn (child_process.js:538:9)
   at Object.execFile (child_process.js:221:15)
   at Object.module.exports.fileCommandJson (/Users/pavel/.fnm/node-versions/v10.15.3/installation/lib/node_modules/@platform-os/marketplace-kit/node_modules/node-notifier/lib/utils.js:81:13)
   at NotificationCenter.notify (/Users/pavel/.fnm/node-versions/v10.15.3/installation/lib/node_modules/@platform-os/marketplace-kit/node_modules/node-notifier/notifiers/notificationcenter.js:81:11)
   at LogStream.stream.on.msg (/Users/pavel/.fnm/node-versions/v10.15.3/installation/lib/node_modules/@platform-os/marketplace-kit/marketplace-kit-logs.js:78:18)
   at LogStream.emit (events.js:194:15)
```

**Comment by pavelloz** [comment]
If it takes more than 2-3h, give up and consider adding flag to disable this thing (disable on CI=true?).

**Comment by pavelloz** [comment]
Turns out E2BIG error is thrown when there is too many args to a command, which means we probably just need to truncate logs entries to not exceed node-notifier limits. Since the notify is a small window it does not need much information anyway.

**Comment by pavelloz** [comment]
Fixed https://github.com/mdyd-dev/pos-cli/commit/be14b935883c10aa295cba440a6312887b930666
