### ISSUE TITLE
Research node-watch replacement

### ISSUE THREAD

**Issue by pavelloz** [mdyd-dev/pos-cli#243]
https://github.com/mdyd-dev/nearme-documentation/issues/635

Instead of documenting bugs, it's better to get rid off them.

**Comment by pavelloz** [comment]
During sleep... looks like node-watch generated path to a directory and passed it forward.

```
shared/address_form.liquid - done
Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:515:3)
    at tryReadSync (fs.js:338:20)
    at Object.readFileSync (fs.js:375:19)
    at Object.fillInTemplateValues (/Users/leming/.nvm/versions/node/v11.8.0/lib/node_modules/@platformos/pos-cli/lib/templates.js:22:23)
    at getBody (/Users/leming/.nvm/versions/node/v11.8.0/lib/node_modules/@platformos/pos-cli/bin/pos-cli-watch.js:36:22)
    at pushFile (/Users/leming/.nvm/versions/node/v11.8.0/lib/node_modules/@platformos/pos-cli/bin/pos-cli-watch.js:51:36)
    at Queue (/Users/leming/.nvm/versions/node/v11.8.0/lib/node_modules/@platformos/pos-cli/bin/pos-cli-watch.js:26:3)
    at /Users/leming/.nvm/versions/node/v11.8.0/lib/node_modules/@platformos/pos-cli/node_modules/async/queue.js:10:5
    at Object.process (/Users/leming/.nvm/versions/node/v11.8.0/lib/node_modules/@platformos/pos-cli/node_modules/async/internal/queue.js:239:17)
    at /Users/leming/.nvm/versions/node/v11.8.0/lib/node_modules/@platformos/pos-cli/node_modules/async/internal/queue.js:97:19
    at Immediate.defer (/Users/leming/.nvm/versions/node/v11.8.0/lib/node_modules/@platformos/pos-cli/node_modules/async/internal/setImmediate.js:17:41)
    at processImmediate (timers.js:632:19)
    at process.topLevelDomainCallback (domain.js:120:23)

[22:21:55] Sync failed.
```
