### ISSUE TITLE
Currently, error returned from pos-cli looks ugly

### ISSUE THREAD

**Issue by jnorbert** [mdyd-dev/pos-cli#261]
## Expected behavior
[500] undefined
 {}

## Actual behavior
Unhandled rejection TypeError: Cannot read property 'slice' of undefined
    at internal (/Users/jaceknorbert/pos-cli/lib/ServerError.js:42:39)
    at tryCatcher (/Users/jaceknorbert/pos-cli/node_modules/bluebird/js/release/util.js:16:23)
    at /Users/jaceknorbert/pos-cli/node_modules/bluebird/js/release/catch_filter.js:34:37
    at tryCatcher (/Users/jaceknorbert/pos-cli/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/jaceknorbert/pos-cli/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/Users/jaceknorbert/pos-cli/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/Users/jaceknorbert/pos-cli/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/Users/jaceknorbert/pos-cli/node_modules/bluebird/js/release/promise.js:695:18)
    at _drainQueueStep (/Users/jaceknorbert/pos-cli/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/Users/jaceknorbert/pos-cli/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/Users/jaceknorbert/pos-cli/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/jaceknorbert/pos-cli/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)

## Version
* pos-cli: 4.0.2
* os: MacOS X

**Comment by pavelloz** [comment]
Yeah, ill fix that one but there's no good fix for that. Server is just returning random gibberish with 3+ different formats that cannot be handled properly, so it's just constant patching.
