### ISSUE TITLE
Not handled: getaddrinfo ENOTFOUND 

### ISSUE THREAD

**Issue by pavelloz** [mdyd-dev/pos-cli#268]
```
Unhandled rejection RequestError: Error: getaddrinfo ENOTFOUND x.staging.oregon.platform-os.com x.staging.oregon.platform-os.com:443
    at new RequestError (/Users/leming/Code/pos-cli/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/leming/Code/pos-cli/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/leming/Code/pos-cli/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/leming/Code/pos-cli/node_modules/request/request.js:185:22)
    at Request.emit (events.js:197:13)
    at Request.onRequestError (/Users/leming/Code/pos-cli/node_modules/request/request.js:881:8)
    at ClientRequest.emit (events.js:197:13)
    at TLSSocket.socketErrorListener (_http_client.js:399:9)
    at TLSSocket.emit (events.js:197:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
```

**Comment by pavelloz** [comment]
Looks like its very low level error (DNS lookups) and reason is not obvious.
