### ISSUE TITLE
Sync showed errors after I deleted a file

### ISSUE THREAD

**Issue by onecreative** [mdyd-dev/pos-cli#375]
## Expected behavior
Delete and sync

## Actual behavior
`(node:49381) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'app/modules/listings/private/model_schemas/booking.yml'
    at Object.openSync (fs.js:439:3)
    at Object.readFileSync (fs.js:344:35)
    at isEmpty (/usr/local/lib/node_modules/@platformos/pos-cli/lib/shouldBeSynced.js:17:6)
    at isNotEmptyYML (/usr/local/lib/node_modules/@platformos/pos-cli/lib/shouldBeSynced.js:30:34)
    at module.exports (/usr/local/lib/node_modules/@platformos/pos-cli/lib/shouldBeSynced.js:73:5)
    at FSWatcher.chokidar.watch.on.on.on.fp (/usr/local/lib/node_modules/@platformos/pos-cli/lib/watch.js:157:27)
    at FSWatcher.emit (events.js:189:13)
    at FSWatcher.emitWithAll (/usr/local/lib/node_modules/@platformos/pos-cli/node_modules/chokidar/index.js:521:8)
    at FSWatcher._emit (/usr/local/lib/node_modules/@platformos/pos-cli/node_modules/chokidar/index.js:613:10)
    at FSWatcher._remove (/usr/local/lib/node_modules/@platformos/pos-cli/node_modules/chokidar/index.js:866:50)
    at FsEventsHandler.handleEvent (/usr/local/lib/node_modules/@platformos/pos-cli/node_modules/chokidar/lib/fsevents-handler.js:257:16)
    at FsEventsHandler.checkFd (/usr/local/lib/node_modules/@platformos/pos-cli/node_modules/chokidar/lib/fsevents-handler.js:246:12)
(node:49381) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:49381) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

## Version

* pos-cli: 4.4.4
* node: 10.15.1
* os: Mac OS 10.15.3

**Comment by pavelloz** [comment]
I think this was fixed in 4.4.5
